cargo-features = ["edition"]

[package]
name = "iex-rust"
version = "0.1.0"
authors = ["toidiu <apoorv@toidiu.com>"]
edition = '2018'


[dependencies]
serde = "~1.0"
serde_derive = "~1.0"
serde_json = "~1.0"
reqwest = "0.9.2"
log = "~0.4"
